package token

import (
	"os"
	"path/filepath"
	"testing"
	"time"

	"Threshold/pkg/storage"
)

func setupTokenStore(t *testing.T) (*Store, func()) {
	t.Helper()
	dir := t.TempDir()
	dbPath := filepath.Join(dir, "test.db")
	store, err := storage.NewBoltStore(dbPath)
	if err != nil {
		t.Fatalf("NewBoltStore: %v", err)
	}
	tokenStore, err := NewStore(store, filepath.Join(dir, "keys"))
	if err != nil {
		t.Fatalf("NewStore: %v", err)
	}
	cleanup := func() {
		store.Close()
		os.RemoveAll(dir)
	}
	return tokenStore, cleanup
}

func TestToken_Generate_Success(t *testing.T) {
	s, cleanup := setupTokenStore(t)
	defer cleanup()

	token, expiresAt, err := s.Generate("admin", 1*time.Hour)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if token == "" {
		t.Fatal("expected non-empty token")
	}
	if expiresAt <= time.Now().UnixMilli() {
		t.Fatal("expires_at should be in the future")
	}
}

func TestToken_Validate_Success(t *testing.T) {
	s, cleanup := setupTokenStore(t)
	defer cleanup()

	tokenStr, _, err := s.Generate("admin", 1*time.Hour)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	entry, err := s.Validate(tokenStr)
	if err != nil {
		t.Fatalf("Validate: %v", err)
	}
	if entry.Token != tokenStr {
		t.Errorf("token mismatch: got %s", entry.Token)
	}
	if entry.Username != "admin" {
		t.Errorf("username mismatch: got %s", entry.Username)
	}
}

func TestToken_Validate_NotFound(t *testing.T) {
	s, cleanup := setupTokenStore(t)
	defer cleanup()

	_, err := s.Validate("nonexistent-token")
	if err == nil {
		t.Fatal("expected error for nonexistent token")
	}
}

func TestToken_Validate_Expired(t *testing.T) {
	s, cleanup := setupTokenStore(t)
	defer cleanup()

	// 生成一个已过期的 token（TTL 为负数）
	tokenStr, _, err := s.Generate("admin", -1*time.Hour)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	_, err = s.Validate(tokenStr)
	if err == nil {
		t.Fatal("expected error for expired token")
	}
}

func TestToken_Revoke_Success(t *testing.T) {
	s, cleanup := setupTokenStore(t)
	defer cleanup()

	tokenStr, _, err := s.Generate("admin", 1*time.Hour)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	// 先验证有效
	if _, err := s.Validate(tokenStr); err != nil {
		t.Fatalf("Validate before revoke: %v", err)
	}

	// 吊销
	if err := s.Revoke(tokenStr); err != nil {
		t.Fatalf("Revoke: %v", err)
	}

	// 再验证应失败
	_, err = s.Validate(tokenStr)
	if err == nil {
		t.Fatal("expected error after revoke")
	}
}

func TestToken_Revoke_NotFound(t *testing.T) {
	s, cleanup := setupTokenStore(t)
	defer cleanup()

	// 吊销不存在的 token 不应报错
	err := s.Revoke("nonexistent-token")
	if err != nil {
		t.Fatalf("Revoke nonexistent: %v", err)
	}
}

func TestToken_MultipleTokens(t *testing.T) {
	s, cleanup := setupTokenStore(t)
	defer cleanup()

	token1, _, _ := s.Generate("admin", 1*time.Hour)
	token2, _, _ := s.Generate("operator", 2*time.Hour)

	// 两个 token 都应有效
	entry1, err := s.Validate(token1)
	if err != nil {
		t.Fatalf("Validate token1: %v", err)
	}
	if entry1.Username != "admin" {
		t.Errorf("token1 username: got %s", entry1.Username)
	}

	entry2, err := s.Validate(token2)
	if err != nil {
		t.Fatalf("Validate token2: %v", err)
	}
	if entry2.Username != "operator" {
		t.Errorf("token2 username: got %s", entry2.Username)
	}

	// 吊销 token1，token2 仍有效
	s.Revoke(token1)

	_, err = s.Validate(token1)
	if err == nil {
		t.Fatal("token1 should be revoked")
	}

	_, err = s.Validate(token2)
	if err != nil {
		t.Fatalf("token2 should still be valid: %v", err)
	}
}

func TestToken_EncKeyAutoGenerated(t *testing.T) {
	dir := t.TempDir()
	dbPath := filepath.Join(dir, "test.db")
	store, err := storage.NewBoltStore(dbPath)
	if err != nil {
		t.Fatalf("NewBoltStore: %v", err)
	}
	defer store.Close()

	keyDir := filepath.Join(dir, "keys")

	// 第一次创建，自动生成 enc.key
	ts1, err := NewStore(store, keyDir)
	if err != nil {
		t.Fatalf("NewStore 1: %v", err)
	}

	// 存一个 token
	tokenStr, _, _ := ts1.Generate("admin", 1*time.Hour)

	// 验证 enc.key 文件存在
	keyPath := filepath.Join(keyDir, "enc.key")
	if _, err := os.Stat(keyPath); os.IsNotExist(err) {
		t.Fatal("enc.key should have been created")
	}

	// 第二次创建，读取已有 enc.key
	ts2, err := NewStore(store, keyDir)
	if err != nil {
		t.Fatalf("NewStore 2: %v", err)
	}

	// 用同一个 enc.key 应能解密之前的 token
	entry, err := ts2.Validate(tokenStr)
	if err != nil {
		t.Fatalf("Validate with reloaded key: %v", err)
	}
	if entry.Username != "admin" {
		t.Errorf("username mismatch: got %s", entry.Username)
	}
}
