// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: pkg/proto/notify.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType 通知事件类型枚举
type EventType int32

const (
	// UNKNOWN 未知事件类型，保留默认值
	EventType_UNKNOWN EventType = 0
	// CONNECTION_OPENED 新连接建立，通知下游准备接收该用户的消息
	EventType_CONNECTION_OPENED EventType = 1
	// CONNECTION_CLOSED 连接关闭，通知下游该会话结束
	EventType_CONNECTION_CLOSED EventType = 2
	// DEVICE_BLACKLISTED 设备被永久拉黑，下游应拒绝该设备的所有后续请求
	EventType_DEVICE_BLACKLISTED EventType = 3
	// ALERT_TRIGGERED 告警触发，通知管理员监控端关注异常行为
	EventType_ALERT_TRIGGERED EventType = 4
	// SCAN_REQUESTED 请求 CICD 模块执行镜像沙箱扫描
	EventType_SCAN_REQUESTED EventType = 5
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CONNECTION_OPENED",
		2: "CONNECTION_CLOSED",
		3: "DEVICE_BLACKLISTED",
		4: "ALERT_TRIGGERED",
		5: "SCAN_REQUESTED",
	}
	EventType_value = map[string]int32{
		"UNKNOWN":            0,
		"CONNECTION_OPENED":  1,
		"CONNECTION_CLOSED":  2,
		"DEVICE_BLACKLISTED": 3,
		"ALERT_TRIGGERED":    4,
		"SCAN_REQUESTED":     5,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_notify_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_pkg_proto_notify_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_notify_proto_rawDescGZIP(), []int{0}
}

// NotifyRequest 下游订阅通知的请求
type NotifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subscriber_id 订阅方唯一标识，用于管理订阅生命周期
	SubscriberId string `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	// events 感兴趣的事件类型列表，为空表示订阅所有事件
	Events        []string `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_pkg_proto_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notify_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *NotifyRequest) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

// NotifyEvent 服务端推送的通知事件
// 每个事件携带完整的上下文信息，下游可根据 event_type 分别处理
type NotifyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id 事件唯一标识，用于去重和幂等处理
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// event_type 事件类型，详见 EventType 枚举定义
	EventType EventType `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=proxy.EventType" json:"event_type,omitempty"`
	// user_id 关联的用户标识
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// connection_id 关联的连接标识（连接事件必填）
	ConnectionId string `protobuf:"bytes,4,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// device_uuid 关联的设备标识（设备拉黑事件必填）
	DeviceUuid string `protobuf:"bytes,5,opt,name=device_uuid,json=deviceUuid,proto3" json:"device_uuid,omitempty"`
	// message 人类可读的事件描述，便于日志记录和告警展示
	Message string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	// timestamp 事件发生时间戳（Unix 毫秒）
	Timestamp int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// metadata 附加元数据，预留扩展
	Metadata      map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyEvent) Reset() {
	*x = NotifyEvent{}
	mi := &file_pkg_proto_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyEvent) ProtoMessage() {}

func (x *NotifyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyEvent.ProtoReflect.Descriptor instead.
func (*NotifyEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notify_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *NotifyEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_UNKNOWN
}

func (x *NotifyEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotifyEvent) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *NotifyEvent) GetDeviceUuid() string {
	if x != nil {
		return x.DeviceUuid
	}
	return ""
}

func (x *NotifyEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotifyEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NotifyEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_pkg_proto_notify_proto protoreflect.FileDescriptor

const file_pkg_proto_notify_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/notify.proto\x12\x05proxy\"L\n" +
	"\rNotifyRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12\x16\n" +
	"\x06events\x18\x02 \x03(\tR\x06events\"\xeb\x02\n" +
	"\vNotifyEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12/\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x10.proxy.EventTypeR\teventType\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12#\n" +
	"\rconnection_id\x18\x04 \x01(\tR\fconnectionId\x12\x1f\n" +
	"\vdevice_uuid\x18\x05 \x01(\tR\n" +
	"deviceUuid\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12<\n" +
	"\bmetadata\x18\b \x03(\v2 .proxy.NotifyEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x87\x01\n" +
	"\tEventType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x15\n" +
	"\x11CONNECTION_OPENED\x10\x01\x12\x15\n" +
	"\x11CONNECTION_CLOSED\x10\x02\x12\x16\n" +
	"\x12DEVICE_BLACKLISTED\x10\x03\x12\x13\n" +
	"\x0fALERT_TRIGGERED\x10\x04\x12\x12\n" +
	"\x0eSCAN_REQUESTED\x10\x05B\x18Z\x16Threshold/pkg/proto/pbb\x06proto3"

var (
	file_pkg_proto_notify_proto_rawDescOnce sync.Once
	file_pkg_proto_notify_proto_rawDescData []byte
)

func file_pkg_proto_notify_proto_rawDescGZIP() []byte {
	file_pkg_proto_notify_proto_rawDescOnce.Do(func() {
		file_pkg_proto_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_notify_proto_rawDesc), len(file_pkg_proto_notify_proto_rawDesc)))
	})
	return file_pkg_proto_notify_proto_rawDescData
}

var file_pkg_proto_notify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_notify_proto_goTypes = []any{
	(EventType)(0),        // 0: proxy.EventType
	(*NotifyRequest)(nil), // 1: proxy.NotifyRequest
	(*NotifyEvent)(nil),   // 2: proxy.NotifyEvent
	nil,                   // 3: proxy.NotifyEvent.MetadataEntry
}
var file_pkg_proto_notify_proto_depIdxs = []int32{
	0, // 0: proxy.NotifyEvent.event_type:type_name -> proxy.EventType
	3, // 1: proxy.NotifyEvent.metadata:type_name -> proxy.NotifyEvent.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_notify_proto_init() }
func file_pkg_proto_notify_proto_init() {
	if File_pkg_proto_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_notify_proto_rawDesc), len(file_pkg_proto_notify_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_notify_proto_goTypes,
		DependencyIndexes: file_pkg_proto_notify_proto_depIdxs,
		EnumInfos:         file_pkg_proto_notify_proto_enumTypes,
		MessageInfos:      file_pkg_proto_notify_proto_msgTypes,
	}.Build()
	File_pkg_proto_notify_proto = out.File
	file_pkg_proto_notify_proto_goTypes = nil
	file_pkg_proto_notify_proto_depIdxs = nil
}
