// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: pkg/proto/proxy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status 决策结果状态码
type Status int32

const (
	// OK 请求放行，raw_http_response 中包含正常的 HTTP 响应
	Status_OK Status = 0
	// BLOCKED 请求被阻断，raw_http_response 为空
	Status_BLOCKED Status = 1
	// BLACKLISTED 设备已被拉黑，后续所有请求将被拒绝
	Status_BLACKLISTED Status = 2
	// RATE_LIMITED 请求被限流，客户端应稍后重试
	Status_RATE_LIMITED Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "BLOCKED",
		2: "BLACKLISTED",
		3: "RATE_LIMITED",
	}
	Status_value = map[string]int32{
		"OK":           0,
		"BLOCKED":      1,
		"BLACKLISTED":  2,
		"RATE_LIMITED": 3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_proxy_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pkg_proto_proxy_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_proxy_proto_rawDescGZIP(), []int{0}
}

// ============================================================
// ProxyRequest 客户端代理发送的请求消息
// 对应原始 HTTP 请求，由 LocalProxy 附加 X-Proxy-* 指纹字段后
// 通过 gRPC 流式传输到服务端。
// ============================================================
type ProxyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection_id 由 EstablishConnection 返回，标识当前会话
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// device_uuid 设备唯一标识，客户端首次启动时采集并持久化
	DeviceUuid string `protobuf:"bytes,2,opt,name=device_uuid,json=deviceUuid,proto3" json:"device_uuid,omitempty"`
	// user_id 用户标识
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// raw_http_request 原始 HTTP 请求字节流
	// 包含完整的请求行、头部（含 X-Proxy-* 指纹字段）和请求体
	RawHttpRequest []byte `protobuf:"bytes,4,opt,name=raw_http_request,json=rawHttpRequest,proto3" json:"raw_http_request,omitempty"`
	// metadata 附加元数据，预留扩展（如链路追踪 ID、请求来源标记等）
	Metadata map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// timestamp 请求发起时间戳（Unix 毫秒）
	Timestamp     int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_pkg_proto_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ProxyRequest) GetDeviceUuid() string {
	if x != nil {
		return x.DeviceUuid
	}
	return ""
}

func (x *ProxyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProxyRequest) GetRawHttpRequest() []byte {
	if x != nil {
		return x.RawHttpRequest
	}
	return nil
}

func (x *ProxyRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProxyRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ============================================================
// ProxyResponse 服务端返回给客户端代理的响应消息
// 客户端根据 status 字段判断请求是否被放行，
// 并将 raw_http_response 还原为 HTTP 响应交还给原生客户端。
// ============================================================
type ProxyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection_id 与请求对应的连接标识
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// raw_http_response 服务端处理后的 HTTP 响应字节流
	RawHttpResponse []byte `protobuf:"bytes,2,opt,name=raw_http_response,json=rawHttpResponse,proto3" json:"raw_http_response,omitempty"`
	// status 决策结果状态码，客户端据此决定是否展示响应
	Status Status `protobuf:"varint,3,opt,name=status,proto3,enum=proxy.Status" json:"status,omitempty"`
	// reason 人类可读的决策原因，便于调试和审计
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_pkg_proto_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ProxyResponse) GetRawHttpResponse() []byte {
	if x != nil {
		return x.RawHttpResponse
	}
	return nil
}

func (x *ProxyResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *ProxyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ============================================================
// ConnectionInit 客户端发起连接初始化请求
// 携带设备指纹信息，服务端据此创建 ConnectionContext
// 并从 PortraitStore 加载该用户的历史画像摘要。
// ============================================================
type ConnectionInit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id 用户标识
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// device_uuid 设备唯一标识
	DeviceUuid string `protobuf:"bytes,2,opt,name=device_uuid,json=deviceUuid,proto3" json:"device_uuid,omitempty"`
	// ip 客户端 IP 地址
	Ip string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	// os_type 操作系统类型（linux / windows / macos）
	OsType string `protobuf:"bytes,4,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	// timestamp 连接发起时间戳（Unix 毫秒）
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInit) Reset() {
	*x = ConnectionInit{}
	mi := &file_pkg_proto_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInit) ProtoMessage() {}

func (x *ConnectionInit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInit.ProtoReflect.Descriptor instead.
func (*ConnectionInit) Descriptor() ([]byte, []int) {
	return file_pkg_proto_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionInit) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConnectionInit) GetDeviceUuid() string {
	if x != nil {
		return x.DeviceUuid
	}
	return ""
}

func (x *ConnectionInit) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ConnectionInit) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *ConnectionInit) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ============================================================
// ConnectionAck 服务端对连接初始化的确认响应
// ============================================================
type ConnectionAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection_id 服务端分配的连接标识，后续 ProxyStream 中使用
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// accepted 连接是否被接受
	// false 通常表示设备已被拉黑或指纹校验失败
	Accepted bool `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// reason 拒绝原因（accepted 为 false 时必填）
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionAck) Reset() {
	*x = ConnectionAck{}
	mi := &file_pkg_proto_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionAck) ProtoMessage() {}

func (x *ConnectionAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionAck.ProtoReflect.Descriptor instead.
func (*ConnectionAck) Descriptor() ([]byte, []int) {
	return file_pkg_proto_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionAck) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectionAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConnectionAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ============================================================
// ConnectionClose 客户端请求关闭连接
// 服务端收到后将 ConnectionContext 持久化到 WAL，
// 更新用户历史画像摘要，释放内存，并通知下游。
// ============================================================
type ConnectionClose struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection_id 要关闭的连接标识
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// timestamp 关闭时间戳（Unix 毫秒）
	Timestamp     int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionClose) Reset() {
	*x = ConnectionClose{}
	mi := &file_pkg_proto_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionClose) ProtoMessage() {}

func (x *ConnectionClose) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionClose.ProtoReflect.Descriptor instead.
func (*ConnectionClose) Descriptor() ([]byte, []int) {
	return file_pkg_proto_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectionClose) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectionClose) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ============================================================
// CloseAck 服务端确认连接已关闭
// ============================================================
type CloseAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success 关闭操作是否成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAck) Reset() {
	*x = CloseAck{}
	mi := &file_pkg_proto_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAck) ProtoMessage() {}

func (x *CloseAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAck.ProtoReflect.Descriptor instead.
func (*CloseAck) Descriptor() ([]byte, []int) {
	return file_pkg_proto_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *CloseAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_proto_proxy_proto protoreflect.FileDescriptor

const file_pkg_proto_proxy_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/proxy.proto\x12\x05proxy\x1a\x14pkg/proto/pull.proto\x1a\x16pkg/proto/notify.proto\"\xb1\x02\n" +
	"\fProxyRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x1f\n" +
	"\vdevice_uuid\x18\x02 \x01(\tR\n" +
	"deviceUuid\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12(\n" +
	"\x10raw_http_request\x18\x04 \x01(\fR\x0erawHttpRequest\x12=\n" +
	"\bmetadata\x18\x05 \x03(\v2!.proxy.ProxyRequest.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\rProxyResponse\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12*\n" +
	"\x11raw_http_response\x18\x02 \x01(\fR\x0frawHttpResponse\x12%\n" +
	"\x06status\x18\x03 \x01(\x0e2\r.proxy.StatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x91\x01\n" +
	"\x0eConnectionInit\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vdevice_uuid\x18\x02 \x01(\tR\n" +
	"deviceUuid\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x17\n" +
	"\aos_type\x18\x04 \x01(\tR\x06osType\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"h\n" +
	"\rConnectionAck\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"T\n" +
	"\x0fConnectionClose\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"$\n" +
	"\bCloseAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*@\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\v\n" +
	"\aBLOCKED\x10\x01\x12\x0f\n" +
	"\vBLACKLISTED\x10\x02\x12\x10\n" +
	"\fRATE_LIMITED\x10\x032\xcc\x02\n" +
	"\rSecurityProxy\x12<\n" +
	"\vProxyStream\x12\x13.proxy.ProxyRequest\x1a\x14.proxy.ProxyResponse(\x010\x01\x12B\n" +
	"\x13EstablishConnection\x12\x15.proxy.ConnectionInit\x1a\x14.proxy.ConnectionAck\x12:\n" +
	"\x0fCloseConnection\x12\x16.proxy.ConnectionClose\x1a\x0f.proxy.CloseAck\x12>\n" +
	"\fPullApproved\x12\x12.proxy.PullRequest\x1a\x16.proxy.ApprovedMessage(\x010\x01\x12=\n" +
	"\x0fSubscribeNotify\x12\x14.proxy.NotifyRequest\x1a\x12.proxy.NotifyEvent0\x01B\x18Z\x16Threshold/pkg/proto/pbb\x06proto3"

var (
	file_pkg_proto_proxy_proto_rawDescOnce sync.Once
	file_pkg_proto_proxy_proto_rawDescData []byte
)

func file_pkg_proto_proxy_proto_rawDescGZIP() []byte {
	file_pkg_proto_proxy_proto_rawDescOnce.Do(func() {
		file_pkg_proto_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_proxy_proto_rawDesc), len(file_pkg_proto_proxy_proto_rawDesc)))
	})
	return file_pkg_proto_proxy_proto_rawDescData
}

var file_pkg_proto_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_proxy_proto_goTypes = []any{
	(Status)(0),             // 0: proxy.Status
	(*ProxyRequest)(nil),    // 1: proxy.ProxyRequest
	(*ProxyResponse)(nil),   // 2: proxy.ProxyResponse
	(*ConnectionInit)(nil),  // 3: proxy.ConnectionInit
	(*ConnectionAck)(nil),   // 4: proxy.ConnectionAck
	(*ConnectionClose)(nil), // 5: proxy.ConnectionClose
	(*CloseAck)(nil),        // 6: proxy.CloseAck
	nil,                     // 7: proxy.ProxyRequest.MetadataEntry
	(*PullRequest)(nil),     // 8: proxy.PullRequest
	(*NotifyRequest)(nil),   // 9: proxy.NotifyRequest
	(*ApprovedMessage)(nil), // 10: proxy.ApprovedMessage
	(*NotifyEvent)(nil),     // 11: proxy.NotifyEvent
}
var file_pkg_proto_proxy_proto_depIdxs = []int32{
	7,  // 0: proxy.ProxyRequest.metadata:type_name -> proxy.ProxyRequest.MetadataEntry
	0,  // 1: proxy.ProxyResponse.status:type_name -> proxy.Status
	1,  // 2: proxy.SecurityProxy.ProxyStream:input_type -> proxy.ProxyRequest
	3,  // 3: proxy.SecurityProxy.EstablishConnection:input_type -> proxy.ConnectionInit
	5,  // 4: proxy.SecurityProxy.CloseConnection:input_type -> proxy.ConnectionClose
	8,  // 5: proxy.SecurityProxy.PullApproved:input_type -> proxy.PullRequest
	9,  // 6: proxy.SecurityProxy.SubscribeNotify:input_type -> proxy.NotifyRequest
	2,  // 7: proxy.SecurityProxy.ProxyStream:output_type -> proxy.ProxyResponse
	4,  // 8: proxy.SecurityProxy.EstablishConnection:output_type -> proxy.ConnectionAck
	6,  // 9: proxy.SecurityProxy.CloseConnection:output_type -> proxy.CloseAck
	10, // 10: proxy.SecurityProxy.PullApproved:output_type -> proxy.ApprovedMessage
	11, // 11: proxy.SecurityProxy.SubscribeNotify:output_type -> proxy.NotifyEvent
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_proxy_proto_init() }
func file_pkg_proto_proxy_proto_init() {
	if File_pkg_proto_proxy_proto != nil {
		return
	}
	file_pkg_proto_pull_proto_init()
	file_pkg_proto_notify_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_proxy_proto_rawDesc), len(file_pkg_proto_proxy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_proxy_proto_goTypes,
		DependencyIndexes: file_pkg_proto_proxy_proto_depIdxs,
		EnumInfos:         file_pkg_proto_proxy_proto_enumTypes,
		MessageInfos:      file_pkg_proto_proxy_proto_msgTypes,
	}.Build()
	File_pkg_proto_proxy_proto = out.File
	file_pkg_proto_proxy_proto_goTypes = nil
	file_pkg_proto_proxy_proto_depIdxs = nil
}
