// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/proto/proxy.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecurityProxy_ProxyStream_FullMethodName         = "/proxy.SecurityProxy/ProxyStream"
	SecurityProxy_EstablishConnection_FullMethodName = "/proxy.SecurityProxy/EstablishConnection"
	SecurityProxy_CloseConnection_FullMethodName     = "/proxy.SecurityProxy/CloseConnection"
	SecurityProxy_PullApproved_FullMethodName        = "/proxy.SecurityProxy/PullApproved"
	SecurityProxy_SubscribeNotify_FullMethodName     = "/proxy.SecurityProxy/SubscribeNotify"
	SecurityProxy_RegisterDevice_FullMethodName      = "/proxy.SecurityProxy/RegisterDevice"
	SecurityProxy_UnregisterDevice_FullMethodName    = "/proxy.SecurityProxy/UnregisterDevice"
	SecurityProxy_ListDevices_FullMethodName         = "/proxy.SecurityProxy/ListDevices"
	SecurityProxy_LoginAdmin_FullMethodName          = "/proxy.SecurityProxy/LoginAdmin"
	SecurityProxy_InitAdmin_FullMethodName           = "/proxy.SecurityProxy/InitAdmin"
)

// SecurityProxyClient is the client API for SecurityProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================
// SecurityProxy 是安全代理的核心 gRPC 服务
// 作为客户端本地代理与 OpenStack 之间的安全网关，
// 负责流量解密、设备身份校验、用户行为评估与访问控制决策。
// ============================================================
type SecurityProxyClient interface {
	// ----------------------------------------------------------
	// ProxyStream
	// 客户端代理通过此双向流发送 HTTP 请求，服务端实时返回决策结果。
	// 流的生命周期与客户端的一次 TCP 会话绑定：
	//
	//	客户端调 EstablishConnection -> 建立 ProxyStream -> 调 CloseConnection
	//
	// ----------------------------------------------------------
	ProxyStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyRequest, ProxyResponse], error)
	// ----------------------------------------------------------
	// EstablishConnection
	// 客户端在发起 ProxyStream 之前调用，携带设备指纹信息，
	// 服务端校验后返回 connection_id，后续所有请求绑定该连接。
	// ----------------------------------------------------------
	EstablishConnection(ctx context.Context, in *ConnectionInit, opts ...grpc.CallOption) (*ConnectionAck, error)
	// ----------------------------------------------------------
	// CloseConnection
	// 客户端主动关闭连接时调用，服务端将 ConnectionContext
	// 通过 WAL 事务持久化，释放内存，通知下游连接已关闭。
	// ----------------------------------------------------------
	CloseConnection(ctx context.Context, in *ConnectionClose, opts ...grpc.CallOption) (*CloseAck, error)
	// ----------------------------------------------------------
	// PullApproved
	// OpenStack 侧通过此接口拉取通过校验的消息。
	// 采用双向流实现：客户端持续发送 PullRequest（含 batch_size），
	// 服务端逐批返回 ApprovedMessage，直到队列为空。
	// ----------------------------------------------------------
	PullApproved(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PullRequest, ApprovedMessage], error)
	// ----------------------------------------------------------
	// SubscribeNotify
	// OpenStack 侧调用此接口订阅实时通知事件，
	// 服务端通过长连接推送连接建立/关闭、设备拉黑、告警等事件。
	// ----------------------------------------------------------
	SubscribeNotify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyEvent], error)
	// ----------------------------------------------------------
	// Admin: Device management
	// ----------------------------------------------------------
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error)
	UnregisterDevice(ctx context.Context, in *UnregisterDeviceRequest, opts ...grpc.CallOption) (*UnregisterDeviceResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginAdminResponse, error)
	InitAdmin(ctx context.Context, in *InitAdminRequest, opts ...grpc.CallOption) (*InitAdminResponse, error)
}

type securityProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityProxyClient(cc grpc.ClientConnInterface) SecurityProxyClient {
	return &securityProxyClient{cc}
}

func (c *securityProxyClient) ProxyStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyRequest, ProxyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SecurityProxy_ServiceDesc.Streams[0], SecurityProxy_ProxyStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProxyRequest, ProxyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecurityProxy_ProxyStreamClient = grpc.BidiStreamingClient[ProxyRequest, ProxyResponse]

func (c *securityProxyClient) EstablishConnection(ctx context.Context, in *ConnectionInit, opts ...grpc.CallOption) (*ConnectionAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionAck)
	err := c.cc.Invoke(ctx, SecurityProxy_EstablishConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityProxyClient) CloseConnection(ctx context.Context, in *ConnectionClose, opts ...grpc.CallOption) (*CloseAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseAck)
	err := c.cc.Invoke(ctx, SecurityProxy_CloseConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityProxyClient) PullApproved(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PullRequest, ApprovedMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SecurityProxy_ServiceDesc.Streams[1], SecurityProxy_PullApproved_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullRequest, ApprovedMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecurityProxy_PullApprovedClient = grpc.BidiStreamingClient[PullRequest, ApprovedMessage]

func (c *securityProxyClient) SubscribeNotify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SecurityProxy_ServiceDesc.Streams[2], SecurityProxy_SubscribeNotify_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NotifyRequest, NotifyEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecurityProxy_SubscribeNotifyClient = grpc.ServerStreamingClient[NotifyEvent]

func (c *securityProxyClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceResponse)
	err := c.cc.Invoke(ctx, SecurityProxy_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityProxyClient) UnregisterDevice(ctx context.Context, in *UnregisterDeviceRequest, opts ...grpc.CallOption) (*UnregisterDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterDeviceResponse)
	err := c.cc.Invoke(ctx, SecurityProxy_UnregisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityProxyClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, SecurityProxy_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityProxyClient) LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginAdminResponse)
	err := c.cc.Invoke(ctx, SecurityProxy_LoginAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityProxyClient) InitAdmin(ctx context.Context, in *InitAdminRequest, opts ...grpc.CallOption) (*InitAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitAdminResponse)
	err := c.cc.Invoke(ctx, SecurityProxy_InitAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityProxyServer is the server API for SecurityProxy service.
// All implementations must embed UnimplementedSecurityProxyServer
// for forward compatibility.
//
// ============================================================
// SecurityProxy 是安全代理的核心 gRPC 服务
// 作为客户端本地代理与 OpenStack 之间的安全网关，
// 负责流量解密、设备身份校验、用户行为评估与访问控制决策。
// ============================================================
type SecurityProxyServer interface {
	// ----------------------------------------------------------
	// ProxyStream
	// 客户端代理通过此双向流发送 HTTP 请求，服务端实时返回决策结果。
	// 流的生命周期与客户端的一次 TCP 会话绑定：
	//
	//	客户端调 EstablishConnection -> 建立 ProxyStream -> 调 CloseConnection
	//
	// ----------------------------------------------------------
	ProxyStream(grpc.BidiStreamingServer[ProxyRequest, ProxyResponse]) error
	// ----------------------------------------------------------
	// EstablishConnection
	// 客户端在发起 ProxyStream 之前调用，携带设备指纹信息，
	// 服务端校验后返回 connection_id，后续所有请求绑定该连接。
	// ----------------------------------------------------------
	EstablishConnection(context.Context, *ConnectionInit) (*ConnectionAck, error)
	// ----------------------------------------------------------
	// CloseConnection
	// 客户端主动关闭连接时调用，服务端将 ConnectionContext
	// 通过 WAL 事务持久化，释放内存，通知下游连接已关闭。
	// ----------------------------------------------------------
	CloseConnection(context.Context, *ConnectionClose) (*CloseAck, error)
	// ----------------------------------------------------------
	// PullApproved
	// OpenStack 侧通过此接口拉取通过校验的消息。
	// 采用双向流实现：客户端持续发送 PullRequest（含 batch_size），
	// 服务端逐批返回 ApprovedMessage，直到队列为空。
	// ----------------------------------------------------------
	PullApproved(grpc.BidiStreamingServer[PullRequest, ApprovedMessage]) error
	// ----------------------------------------------------------
	// SubscribeNotify
	// OpenStack 侧调用此接口订阅实时通知事件，
	// 服务端通过长连接推送连接建立/关闭、设备拉黑、告警等事件。
	// ----------------------------------------------------------
	SubscribeNotify(*NotifyRequest, grpc.ServerStreamingServer[NotifyEvent]) error
	// ----------------------------------------------------------
	// Admin: Device management
	// ----------------------------------------------------------
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error)
	UnregisterDevice(context.Context, *UnregisterDeviceRequest) (*UnregisterDeviceResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	LoginAdmin(context.Context, *LoginAdminRequest) (*LoginAdminResponse, error)
	InitAdmin(context.Context, *InitAdminRequest) (*InitAdminResponse, error)
	mustEmbedUnimplementedSecurityProxyServer()
}

// UnimplementedSecurityProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecurityProxyServer struct{}

func (UnimplementedSecurityProxyServer) ProxyStream(grpc.BidiStreamingServer[ProxyRequest, ProxyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ProxyStream not implemented")
}
func (UnimplementedSecurityProxyServer) EstablishConnection(context.Context, *ConnectionInit) (*ConnectionAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstablishConnection not implemented")
}
func (UnimplementedSecurityProxyServer) CloseConnection(context.Context, *ConnectionClose) (*CloseAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseConnection not implemented")
}
func (UnimplementedSecurityProxyServer) PullApproved(grpc.BidiStreamingServer[PullRequest, ApprovedMessage]) error {
	return status.Errorf(codes.Unimplemented, "method PullApproved not implemented")
}
func (UnimplementedSecurityProxyServer) SubscribeNotify(*NotifyRequest, grpc.ServerStreamingServer[NotifyEvent]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeNotify not implemented")
}
func (UnimplementedSecurityProxyServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedSecurityProxyServer) UnregisterDevice(context.Context, *UnregisterDeviceRequest) (*UnregisterDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterDevice not implemented")
}
func (UnimplementedSecurityProxyServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedSecurityProxyServer) LoginAdmin(context.Context, *LoginAdminRequest) (*LoginAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAdmin not implemented")
}
func (UnimplementedSecurityProxyServer) InitAdmin(context.Context, *InitAdminRequest) (*InitAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitAdmin not implemented")
}
func (UnimplementedSecurityProxyServer) mustEmbedUnimplementedSecurityProxyServer() {}
func (UnimplementedSecurityProxyServer) testEmbeddedByValue()                       {}

// UnsafeSecurityProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityProxyServer will
// result in compilation errors.
type UnsafeSecurityProxyServer interface {
	mustEmbedUnimplementedSecurityProxyServer()
}

func RegisterSecurityProxyServer(s grpc.ServiceRegistrar, srv SecurityProxyServer) {
	// If the following call pancis, it indicates UnimplementedSecurityProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecurityProxy_ServiceDesc, srv)
}

func _SecurityProxy_ProxyStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SecurityProxyServer).ProxyStream(&grpc.GenericServerStream[ProxyRequest, ProxyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecurityProxy_ProxyStreamServer = grpc.BidiStreamingServer[ProxyRequest, ProxyResponse]

func _SecurityProxy_EstablishConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionInit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityProxyServer).EstablishConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityProxy_EstablishConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityProxyServer).EstablishConnection(ctx, req.(*ConnectionInit))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityProxy_CloseConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionClose)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityProxyServer).CloseConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityProxy_CloseConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityProxyServer).CloseConnection(ctx, req.(*ConnectionClose))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityProxy_PullApproved_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SecurityProxyServer).PullApproved(&grpc.GenericServerStream[PullRequest, ApprovedMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecurityProxy_PullApprovedServer = grpc.BidiStreamingServer[PullRequest, ApprovedMessage]

func _SecurityProxy_SubscribeNotify_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NotifyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SecurityProxyServer).SubscribeNotify(m, &grpc.GenericServerStream[NotifyRequest, NotifyEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecurityProxy_SubscribeNotifyServer = grpc.ServerStreamingServer[NotifyEvent]

func _SecurityProxy_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityProxyServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityProxy_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityProxyServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityProxy_UnregisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityProxyServer).UnregisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityProxy_UnregisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityProxyServer).UnregisterDevice(ctx, req.(*UnregisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityProxy_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityProxyServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityProxy_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityProxyServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityProxy_LoginAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityProxyServer).LoginAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityProxy_LoginAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityProxyServer).LoginAdmin(ctx, req.(*LoginAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityProxy_InitAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityProxyServer).InitAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityProxy_InitAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityProxyServer).InitAdmin(ctx, req.(*InitAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecurityProxy_ServiceDesc is the grpc.ServiceDesc for SecurityProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecurityProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.SecurityProxy",
	HandlerType: (*SecurityProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EstablishConnection",
			Handler:    _SecurityProxy_EstablishConnection_Handler,
		},
		{
			MethodName: "CloseConnection",
			Handler:    _SecurityProxy_CloseConnection_Handler,
		},
		{
			MethodName: "RegisterDevice",
			Handler:    _SecurityProxy_RegisterDevice_Handler,
		},
		{
			MethodName: "UnregisterDevice",
			Handler:    _SecurityProxy_UnregisterDevice_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _SecurityProxy_ListDevices_Handler,
		},
		{
			MethodName: "LoginAdmin",
			Handler:    _SecurityProxy_LoginAdmin_Handler,
		},
		{
			MethodName: "InitAdmin",
			Handler:    _SecurityProxy_InitAdmin_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProxyStream",
			Handler:       _SecurityProxy_ProxyStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PullApproved",
			Handler:       _SecurityProxy_PullApproved_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeNotify",
			Handler:       _SecurityProxy_SubscribeNotify_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/proto/proxy.proto",
}
