// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go router_v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/pull.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PullRequest OpenStack 侧拉取已通过的消息
type PullRequest struct {
	state protoimpl.MessageState `protogen:"open.router_v1"`
	// subscriber_id 拉取方唯一标识，用于区分不同的下游消费者
	SubscriberId string `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	// batch_size 单次拉取的最大消息数量，服务端按此上限返回
	BatchSize int32 `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// timestamp 拉取请求发起时间戳（Unix 毫秒）
	Timestamp     int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_pkg_proto_pull_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pull_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pull_proto_rawDescGZIP(), []int{0}
}

func (x *PullRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *PullRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *PullRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ApprovedMessage 服务端返回的已通过校验的消息
// 包含原始请求和响应，以及决策引擎的判定结果，
// 供 OpenStack 侧进行后续处理（如审计日志、操作执行）。
type ApprovedMessage struct {
	state protoimpl.MessageState `protogen:"open.router_v1"`
	// message_id 消息唯一标识，用于去重和幂等处理
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// connection_id 该消息对应的连接标识
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// raw_http_request 原始 HTTP 请求字节流
	RawHttpRequest []byte `protobuf:"bytes,3,opt,name=raw_http_request,json=rawHttpRequest,proto3" json:"raw_http_request,omitempty"`
	// raw_http_response 服务端转发后的 HTTP 响应字节流
	RawHttpResponse []byte `protobuf:"bytes,4,opt,name=raw_http_response,json=rawHttpResponse,proto3" json:"raw_http_response,omitempty"`
	// decision_action 决策引擎的动作类型（ALLOW / AUDIT / ALERT 等）
	DecisionAction string `protobuf:"bytes,5,opt,name=decision_action,json=decisionAction,proto3" json:"decision_action,omitempty"`
	// decision_reason 决策原因描述，便于审计追溯
	DecisionReason string `protobuf:"bytes,6,opt,name=decision_reason,json=decisionReason,proto3" json:"decision_reason,omitempty"`
	// timestamp 消息生成时间戳（Unix 毫秒）
	Timestamp     int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovedMessage) Reset() {
	*x = ApprovedMessage{}
	mi := &file_pkg_proto_pull_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovedMessage) ProtoMessage() {}

func (x *ApprovedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pull_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovedMessage.ProtoReflect.Descriptor instead.
func (*ApprovedMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pull_proto_rawDescGZIP(), []int{1}
}

func (x *ApprovedMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ApprovedMessage) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ApprovedMessage) GetRawHttpRequest() []byte {
	if x != nil {
		return x.RawHttpRequest
	}
	return nil
}

func (x *ApprovedMessage) GetRawHttpResponse() []byte {
	if x != nil {
		return x.RawHttpResponse
	}
	return nil
}

func (x *ApprovedMessage) GetDecisionAction() string {
	if x != nil {
		return x.DecisionAction
	}
	return ""
}

func (x *ApprovedMessage) GetDecisionReason() string {
	if x != nil {
		return x.DecisionReason
	}
	return ""
}

func (x *ApprovedMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pkg_proto_pull_proto protoreflect.FileDescriptor

const file_pkg_proto_pull_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/pull.proto\x12\x05proxy\"o\n" +
	"\vPullRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x02 \x01(\x05R\tbatchSize\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x9b\x02\n" +
	"\x0fApprovedMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12(\n" +
	"\x10raw_http_request\x18\x03 \x01(\fR\x0erawHttpRequest\x12*\n" +
	"\x11raw_http_response\x18\x04 \x01(\fR\x0frawHttpResponse\x12'\n" +
	"\x0fdecision_action\x18\x05 \x01(\tR\x0edecisionAction\x12'\n" +
	"\x0fdecision_reason\x18\x06 \x01(\tR\x0edecisionReason\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestampB\x18Z\x16Threshold/pkg/proto/pbb\x06proto3"

var (
	file_pkg_proto_pull_proto_rawDescOnce sync.Once
	file_pkg_proto_pull_proto_rawDescData []byte
)

func file_pkg_proto_pull_proto_rawDescGZIP() []byte {
	file_pkg_proto_pull_proto_rawDescOnce.Do(func() {
		file_pkg_proto_pull_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_pull_proto_rawDesc), len(file_pkg_proto_pull_proto_rawDesc)))
	})
	return file_pkg_proto_pull_proto_rawDescData
}

var file_pkg_proto_pull_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_pull_proto_goTypes = []any{
	(*PullRequest)(nil),     // 0: proxy.PullRequest
	(*ApprovedMessage)(nil), // 1: proxy.ApprovedMessage
}
var file_pkg_proto_pull_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_pull_proto_init() }
func file_pkg_proto_pull_proto_init() {
	if File_pkg_proto_pull_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_pull_proto_rawDesc), len(file_pkg_proto_pull_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_pull_proto_goTypes,
		DependencyIndexes: file_pkg_proto_pull_proto_depIdxs,
		MessageInfos:      file_pkg_proto_pull_proto_msgTypes,
	}.Build()
	File_pkg_proto_pull_proto = out.File
	file_pkg_proto_pull_proto_goTypes = nil
	file_pkg_proto_pull_proto_depIdxs = nil
}
